#list is mutable
#list is ordered
user_input = input("")
my_list = list(map(int,user_input.split()))
#Methods in list:
#1. append()
my_list.append(6)
print("This is appended list with 6 :",my_list)
#2. extend()
my_list.extend([7,8,9])
print("this is an extended list : ",my_list)
#3. insert()
my_list.insert(11,11)
print("this is an inserted list : ",my_list)
#4. remove()
my_list.remove(5)  
print("this is a removed list : ",my_list)
#5. pop()
my_list.pop(0)
print("this is a popped list : ",my_list)
#6. index()
print("This is index(2) list : ",my_list.index(2))
#7. count()
print("This is count(2) list : ",my_list.count(2))
#8. sort()
my_list.sort()
print("This is sorted list : ",my_list)
#9. reverse()
my_list.reverse()
print("This is reversed list : ",my_list)
#10. copy()
new_list = my_list.copy()
print("This is copied list : ",new_list)
print(new_list)
#11. clear()
my_list.clear()
print("This is cleared list : ",my_list)
#12. len()
print("The lenght of the list : ",len(new_list))
#13. max()
print("The maximum value in the list : ",max(new_list))
#14. min()
print("The minimum value in the list : ",min(new_list))
#15. sum()
print("The sum of the list : ",sum(new_list))
#16. any()
print("Is there any value in the list : ",any(new_list))
#17. all()
print("Is all values in the list : ",all(new_list))